name: 🎉 PR closed

on:
  pull_request_target: # zizmor: ignore[dangerous-triggers]
    types:
      - closed

permissions: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  thank-you:
    name: Post thank you comment
    runs-on: ubuntu-slim
    if: ${{ github.event.pull_request.merged == true && github.event.pull_request.user.login != 'renovate[bot]' }}

    permissions:
      contents: read
      pull-requests: write # Required to post comments on pull requests

    steps:
      - name: 🙏 Post Thank You Comment
        uses: actions/github-script@3a2844b7e9c422d3c10d287c895573f7108da1b3 # v9
        env:
          comment: |
            ## Merge Successful

            Thanks for your contribution! 🎉

            The changes will be part of the upcoming update of this plugin.
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: process.env.comment
            })
