on: [workflow_call]

jobs:
  test:
    name: 🧪 Tests
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - name: 📥 Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          sparse-checkout-cone-mode: false
          # Download only the necessary files
          sparse-checkout: |
            src
            tests
            package.json
            bun.lock
            bunfig.toml
            tsup.config.ts
            tsconfig*.json
            !**/*.md

      - name: 🔧 Setup Bun
        uses: oven-sh/setup-bun@4bc047ad259df6fc24a6c9b0f9a0cb08cf17fbe5 # v2
        with:
          bun-version: latest

      - name: 📥 Cache Bun dependencies
        # Run only on Windows because on Linux there are no problems with slow package installation
        if: matrix.os == 'windows-latest'
        uses: actions/cache@5a3ec84eff668545956fd18022155c47e93e2684 # v4
        with:
          path: |
            ~\.bun
          key: ${{ runner.os }}-bun-${{ hashFiles('**/bun.lock') }}

      - name: 📦 Install dependencies
        run: bun install --frozen-lockfile

      - name: 🧪 Run tests
        run: bun run test
